# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 220)

        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName('centralwidget')

        self.toolButton = QtWidgets.QToolButton(Dialog)
        self.toolButton.setEnabled(True)
        self.toolButton = QtWidgets.QPushButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(190, 150, 81, 31))
        self.toolButton.setStyleSheet("font: 75 12pt \"Aharoni\";")
        self.toolButton.setObjectName("toolButton")


        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(90, 60, 401, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.toolButton_2 = QtWidgets.QToolButton(Dialog)
        self.toolButton_2.setEnabled(True)
        self.toolButton_2.setGeometry(QtCore.QRect(320, 150, 81, 31))
        self.toolButton_2.setStyleSheet("font: 75 12pt \"Aharoni\";")
        self.toolButton_2.setObjectName("toolButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.toolButton.setText(_translate("Dialog", "FILE"))
        self.toolButton_2.setText(_translate("Dialog", "converse"))
